export const typography = {
  h1: {
    fontSize: "6rem",
    fontFamily: "Roboto, sans-serif",
    paragraphIndent: 0,
    paragraphSpacing: 0,
    fontWeight: 300,
    letterSpacing: "-0.0938rem",
    lineHeight: "7rem",
  },
  h2: {
    fontSize: "3.75rem",
    fontFamily: "Roboto, sans-serif",
    paragraphIndent: 0,
    paragraphSpacing: 0,
    fontWeight: 300,
    letterSpacing: "-0.0313rem",
    lineHeight: "4.5rem",
  },
  h3: {
    fontSize: "2.8125rem",
    fontFamily: "Roboto, sans-serif",
    paragraphIndent: 0,
    paragraphSpacing: 0,
    fontWeight: 300,
    letterSpacing: "-2%",
    lineHeight: "3.25rem",
  },
  h4: {
    fontSize: "2.125rem",
    fontFamily: "Roboto, sans-serif",
    paragraphIndent: 0,
    paragraphSpacing: 0,
    fontWeight: 300,
    letterSpacing: "0rem",
    lineHeight: "2.25rem",
  },
  h5: {
    fontSize: "1.5rem",
    fontFamily: "Roboto, sans-serif",
    paragraphIndent: 0,
    paragraphSpacing: 0,
    fontWeight: 400,
    letterSpacing: "0.0113rem",
    lineHeight: "2rem",
  },
  h6: {
    fontSize: "1.5rem",
    fontFamily: "Roboto, sans-serif",
    paragraphIndent: 0,
    paragraphSpacing: 0,
    fontWeight: 600,
    letterSpacing: "0rem",
    lineHeight: "1.75rem",
  },
  subtitle1: {
    fontSize: "1rem",
    fontFamily: "Roboto, sans-serif",
    paragraphIndent: 0,
    paragraphSpacing: 0,
    fontWeight: 500,
    letterSpacing: "0rem",
    lineHeight: "1.375rem",
  },
  subtitle2: {
    fontSize: "0.875rem",
    fontFamily: "Roboto, sans-serif",
    paragraphIndent: 0,
    paragraphSpacing: 0,
    fontWeight: 500,
    letterSpacing: "0.0063rem",
    lineHeight: "1.125rem",
  },
  body1: {
    fontSize: "1.125rem",
    fontFamily: "Roboto, sans-serif",
    paragraphIndent: 0,
    paragraphSpacing: 0,
    fontWeight: 400,
    letterSpacing: "0rem",
    lineHeight: "1.5rem",
  },
  body2: {
    fontSize: "1rem",
    fontFamily: "Roboto, sans-serif",
    paragraphIndent: 0,
    paragraphSpacing: 0,
    fontWeight: 400,
    letterSpacing: "0rem",
    lineHeight: "1.375rem",
  },
  body3: {
    fontSize: "0.875rem",
    fontFamily: "Roboto, sans-serif",
    paragraphIndent: 0,
    paragraphSpacing: 0,
    fontWeight: 400,
    letterSpacing: "0rem",
    lineHeight: "1.25rem",
  },
  body4: {
    fontSize: "0.75rem",
    fontFamily: "Roboto, sans-serif",
    paragraphIndent: 0,
    paragraphSpacing: 0,
    fontWeight: 400,
    letterSpacing: "0rem",
    lineHeight: "1rem",
  },
  button: {
    fontSize: "1rem",
    fontFamily: "Roboto, sans-serif",
    paragraphIndent: 0,
    paragraphSpacing: 0,
    fontWeight: 600,
    letterSpacing: "0%",
    lineHeight: "1.375rem",
    textTransform: "none" as const,
  },
  overline: {
    fontSize: "0.625rem",
    fontFamily: "Roboto, sans-serif",
    paragraphIndent: 0,
    paragraphSpacing: 0,
    fontWeight: 500,
    letterSpacing: "0.0938rem",
    lineHeight: "1rem",
  },
};
